name : Infrastructure Deployment to Aws using Terraform with Multi Environment in Github Actions

"on":
  push:
    branches:
      - multi-stage

permissions:
  id-token: write
  contents: read
 

jobs:
  terraform:
    name: Terraform - ${{ matrix.environment }}
    runs-on: ubuntu-latest

    strategy:
      matrix:
        environment:
          - dev
          - stage

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.14.0

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::920411896934:role/Github-terraform-access
          aws-region: us-east-1

      - name: Terraform Init
        working-directory: "./${{ matrix.environment }}"
        run: terraform init

      - name: Terraform Validate
        working-directory: "./${{ matrix.environment }}"
        run: terraform validate

      - name: Terraform Plan
        working-directory: "./${{ matrix.environment }}"
        run: terraform plan

      - name: Terraform Destroy
        working-directory: "./${{ matrix.environment }}"  
        run: terraform destroy -auto-approve